"""
app.py
CROPWISE AI - Smart Crop Recommendation System & Farm Advisory Engine
Academic ML Project: Decision Tree Classifier (CART Algorithm)
Preserves all original project architecture, authentication, OTP verification,
ML inference, farm ledger, crop advisory modules, and government scheme eligibility.
"""

import os
import sys
import json
import time
import random
import datetime
import urllib.request
from functools import wraps

from flask import (
    Flask,
    request,
    session,
    render_template,
    redirect,
    url_for,
    flash,
    jsonify
)
from werkzeug.security import generate_password_hash
import joblib
import numpy as np
import pandas as pd

from database.db import (
    init_db,
    create_user,
    delete_unverified_user,
    update_user_otp,
    get_user_otp_state,
    verify_user_otp,
    authenticate_user,
    get_user_by_id,
    get_user_by_email,
    verify_reset_otp,
    update_user_password,
    update_user_profile,
    save_recommendation,
    get_recommendation_history,
    get_recommendation_by_id,
    delete_recommendation,
    add_expense,
    get_user_expenses,
    get_expense_summary,
    delete_expense,
    add_note,
    get_user_notes,
    delete_note,
    add_reminder,
    get_user_reminders,
    toggle_reminder,
    delete_reminder,
)

# -------------------------------------------------------------
# FLASK APPLICATION CONFIGURATION
# -------------------------------------------------------------

app = Flask(__name__)

# Ensure SECRET_KEY is never empty or falsy
secret = (os.environ.get("SECRET_KEY") or "").strip() or "cropwise_ai_secret_super_key_2026_final_year"
app.secret_key = secret
app.config["SECRET_KEY"] = secret

# Initialize database tables on startup
try:
    init_db()
except Exception as e:
    print(f"[WARN] Database initialization notice: {e}")



# -------------------------------------------------------------
# EMAILJS CONFIGURATION (FOR REGISTRATION OTP)
# -------------------------------------------------------------

EMAILJS_SERVICE_ID = os.environ.get("EMAILJS_SERVICE_ID", "service_was0ejd")
EMAILJS_TEMPLATE_ID = os.environ.get("EMAILJS_TEMPLATE_ID", "template_wz05yvm")
EMAILJS_PUBLIC_KEY = os.environ.get("EMAILJS_PUBLIC_KEY", "U4lSN1hFTXTfz7mMV")
EMAILJS_PRIVATE_KEY = os.environ.get("EMAILJS_PRIVATE_KEY", "")

def send_otp_email(recipient_email, otp_code, origin_url=None):
    """
    Sends the exact 6-digit OTP to the farmer's entered email using EmailJS REST API.
    Uses the exact EmailJS template variables:
      - email: recipient email address
      - passcode: exact 6-digit OTP generated by Flask
      - time: validity and timestamp information
    """
    now_str = datetime.datetime.now().strftime("%I:%M %p, %d %b %Y")
    time_str = f"5 minutes (Generated at {now_str})"

    payload = {
        "service_id": EMAILJS_SERVICE_ID,
        "template_id": EMAILJS_TEMPLATE_ID,
        "user_id": EMAILJS_PUBLIC_KEY,
        "template_params": {
            "email": recipient_email,
            "passcode": str(otp_code),
            "time": time_str
        }
    }

    if EMAILJS_PRIVATE_KEY and EMAILJS_PRIVATE_KEY.strip():
        payload["accessToken"] = EMAILJS_PRIVATE_KEY.strip()

    base_origin = (origin_url or "http://localhost:5000").rstrip("/")
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Origin": base_origin,
        "Referer": f"{base_origin}/register"
    }

    try:
        req = urllib.request.Request(
            "https://api.emailjs.com/api/v1.0/email/send",
            data=json.dumps(payload).encode("utf-8"),
            headers=headers,
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=12) as response:
            if response.status == 200:
                print(f"[OK] OTP {otp_code} successfully delivered to {recipient_email} via EmailJS.")
                return True, None
    except urllib.error.HTTPError as e:
        err_msg = e.read().decode("utf-8", errors="ignore")
        print(f"[ERROR] EmailJS HTTP Error {e.code} for {recipient_email}: {err_msg}")
        return False, f"Email delivery error ({e.code})"
    except Exception as e:
        print(f"[ERROR] EmailJS delivery error for {recipient_email}: {e}")
        return False, "Could not connect to email delivery service"
    return True, None

def check_smtp_connection():
    """Optional diagnostic helper to test SMTP reachability if requested via CLI."""
    smtp_server = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", 587))
    smtp_user = os.environ.get("SMTP_USERNAME") or os.environ.get("SENDER_EMAIL")
    smtp_pass = os.environ.get("SMTP_PASSWORD")
    if not smtp_user or not smtp_pass:
        print("[INFO] SMTP credentials not configured (EmailJS is used by default).")
        return True
    import smtplib
    try:
        server = smtplib.SMTP(smtp_server, smtp_port, timeout=10)
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.quit()
        print("[OK] SMTP connection verified.")
        return True
    except Exception as e:
        print(f"[ERROR] SMTP connection check failed: {e}")
        return False

# -------------------------------------------------------------
# CROP KNOWLEDGE BASE & ML MODEL LOADING
# -------------------------------------------------------------

CROP_DB_PATH = os.path.join(os.path.dirname(__file__), "crop_database.json")
if os.path.exists(CROP_DB_PATH):
    with open(CROP_DB_PATH, "r", encoding="utf-8") as f:
        crop_database = json.load(f)
else:
    crop_database = {}

MODEL_PATH = os.path.join(os.path.dirname(__file__), "models", "crop_decision_tree.pkl")
dt_model = None
soil_encoder = None
crop_encoder = None
feature_cols = ['Soil_Type_Encoded', 'pH', 'Temperature', 'Humidity', 'Rainfall']

if os.path.exists(MODEL_PATH):
    try:
        model_bundle = joblib.load(MODEL_PATH)
        dt_model = model_bundle.get("model")
        soil_encoder = model_bundle.get("soil_encoder")
        crop_encoder = model_bundle.get("crop_encoder")
        feature_cols = model_bundle.get("feature_cols", feature_cols)
        print("[OK] Loaded trained Decision Tree model bundle successfully.")
    except Exception as e:
        print(f"[WARN] Could not load ML model bundle: {e}")

# -------------------------------------------------------------
# AUTHENTICATION DECORATOR
# -------------------------------------------------------------

def login_required(f):
    """Decorator to protect routes requiring logged-in farmer session."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user_id" not in session:
            flash("Please log in to access this feature.", "warning")
            return redirect(url_for("login"))
        return f(*args, **kwargs)
    return decorated_function

# -------------------------------------------------------------
# TEMPLATE GLOBAL CONTEXT PROCESSOR
# -------------------------------------------------------------

@app.context_processor
def inject_global_context():
    """Inject global context variables available across all templates."""
    user_id = session.get("user_id")
    last_rec = None
    if user_id:
        try:
            history = get_recommendation_history(user_id, limit=1)
            if history:
                last_rec = history[0]
        except Exception:
            pass
    return {
        "current_year": datetime.datetime.now().year,
        "last_rec": last_rec,
        "crop_database": crop_database
    }

# -------------------------------------------------------------
# GOVERNMENT SCHEMES DATASET
# -------------------------------------------------------------

GOVT_SCHEMES = [
    # 1. Crop-specific schemes/support
    {
        "id": "nfsm-rice-pulses",
        "name": "National Food Security Mission (NFSM) - Rice, Wheat & Pulses",
        "category": "Crop-specific schemes/support",
        "department": "Ministry of Agriculture & Farmers Welfare, Govt of India / TN Agrisnet",
        "purpose": "Demonstrations on improved package of practices, high-yielding seed distribution, micro-nutrients, soil ameliorants, and plant protection chemicals at subsidized rates.",
        "deadline": "Season-based (Kharif / Rabi / Summer)",
        "method": "Apply at Block Assistant Director of Agriculture (ADA) office or online via TN AGRISNET",
        "documents": ["Aadhaar Card", "Land Patta/Chitta", "Soil Health Card", "Bank Passbook", "Passport Size Photograph"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Paddy", "Wheat", "Black Gram", "Chickpea", "Millets", "Maize"]
    },
    {
        "id": "midh-horticulture",
        "name": "Mission for Integrated Development of Horticulture (MIDH) - Fruits & Plantation",
        "category": "Crop-specific schemes/support",
        "department": "Department of Horticulture and Plantation Crops, Govt of Tamil Nadu",
        "purpose": "Subsidies for cultivation of high-value horticultural crops (Banana, Coconut, Tea, Coffee), high-density planting, nursery establishment, and post-harvest pack houses.",
        "deadline": "Target-based allocation (Open for current financial year)",
        "method": "Apply online at TNHorticulture portal or at Block Assistant Director of Horticulture (ADH) office",
        "documents": ["Aadhaar Card", "Patta/Chitta/Adangal", "Field Photo", "Ration Card / Smart Card", "Bank Passbook"],
        "url": "https://tnhorticulture.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Banana", "Coconut", "Coffee", "Tea"]
    },
    {
        "id": "cotton-development-scheme",
        "name": "Special Cotton Development Scheme & Technology Mission on Cotton",
        "category": "Crop-specific schemes/support",
        "department": "Department of Agriculture, Govt of Tamil Nadu",
        "purpose": "Subsidized distribution of certified/hybrid cotton seeds, pheromone traps, biopesticides, and machine-picking demonstrations for cotton growers.",
        "deadline": "Pre-Kharif and Winter sowing season",
        "method": "Contact local Agricultural Extension Center (AEC) / Uzhavan App",
        "documents": ["Aadhaar Card", "Chitta/Adangal copy", "Bank Passbook"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Maharashtra", "Gujarat"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Cotton"]
    },
    {
        "id": "sugarcane-development-mission",
        "name": "Sustainable Sugarcane Initiative (SSI) & Transitional Assistance",
        "category": "Crop-specific schemes/support",
        "department": "Directorate of Sugar & Agriculture Department, Govt of Tamil Nadu",
        "purpose": "Financial incentive for single bud chip nursery raising, drip fertigation subsidy (100% for Small/Marginal farmers), and harvest machinery assistance.",
        "deadline": "Special / Main planting season",
        "method": "Apply through respective Co-operative / Private Sugar Mills or Agriculture Department",
        "documents": ["Aadhaar Card", "Sugar Mill registration agreement", "Land Patta/Chitta", "Bank Passbook"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Maharashtra"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Sugarcane"]
    },
    {
        "id": "jute-icare-mission",
        "name": "Jute-ICARE (Improved Cultivation and Advanced Retting Exercise)",
        "category": "Crop-specific schemes/support",
        "department": "National Jute Board, Ministry of Textiles & Ministry of Agriculture, Govt of India",
        "purpose": "Subsidized certified jute seeds, microbial consortium (SONA) for accelerated retting, and seed drill implements.",
        "deadline": "Pre-monsoon sowing season",
        "method": "Apply via National Jute Board / Jute Corporation of India (JCI) portal",
        "documents": ["Aadhaar Card", "Land possession certificate", "Bank Passbook"],
        "url": "http://www.jute.com",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Andhra Pradesh", "West Bengal", "Bihar", "Odisha", "Assam"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Jute"]
    },
    {
        "id": "oilseeds-development-scheme",
        "name": "National Mission on Edible Oils - Oilseeds (NMEO-OS) / Groundnut Support",
        "category": "Crop-specific schemes/support",
        "department": "Department of Agriculture and Farmers Welfare, Govt of Tamil Nadu",
        "purpose": "Quality seed subsidies, gypsum distribution, bio-fertilizer supply, and sprinkler sets for groundnut and other oilseed farmers.",
        "deadline": "Season-wise (Chithirai / Adi / Karthigai pattam)",
        "method": "Agricultural Extension Centre (AEC) / Uzhavan App",
        "documents": ["Aadhaar Card", "Land Patta/Chitta", "Bank Passbook"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Gujarat", "Maharashtra", "Rajasthan"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Groundnut"]
    },

    # 2. General farmer assistance schemes
    {
        "id": "pm-kisan",
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "category": "General farmer assistance schemes",
        "department": "Department of Agriculture & Farmers Welfare, Govt. of India",
        "purpose": "Direct income support of ₹6,000 per year paid in three equal 4-monthly installments of ₹2,000 directly into the bank accounts of landholding farmer families.",
        "deadline": "Open throughout the year",
        "method": "Online via pmkisan.gov.in or Common Service Centres (CSC) / State Agriculture Extension Offices",
        "documents": ["Aadhaar Card", "Land Ownership Record (Patta / Chitta)", "Aadhaar-seeded Bank Account Passbook", "Active Mobile Number"],
        "url": "https://pmkisan.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "tn-kalaignar-scheme",
        "name": "Kalaignarin All Village Integrated Agricultural Development Programme (KAVIADP)",
        "category": "General farmer assistance schemes",
        "department": "Department of Agriculture and Farmers Welfare, Govt of Tamil Nadu",
        "purpose": "Integrated village-level farm development providing free coconut saplings, horticulture toolkits, pulse seeds, and dryland irrigation infrastructure.",
        "deadline": "Active annual target villages",
        "method": "Village Agricultural Officer (VAO) / Block Assistant Director of Agriculture",
        "documents": ["Aadhaar Card", "Smart Family Card (Ration Card)", "Land Patta/Chitta"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "pm-kisan-maandhan",
        "name": "Pradhan Mantri Kisan Maandhan Yojana (PM-KMY)",
        "category": "General farmer assistance schemes",
        "department": "Ministry of Agriculture & Farmers Welfare / Life Insurance Corporation of India (LIC)",
        "purpose": "Old age pension scheme providing an assured monthly pension of ₹3,000 to small and marginal farmers (18-40 years entry age) upon attaining 60 years of age.",
        "deadline": "Open enrollment throughout the year",
        "method": "Common Service Centres (CSC) or online through maandhan.in",
        "documents": ["Aadhaar Card", "Savings Bank Account details / Passbook", "Copy of Land Document (Patta/Chitta < 5 acres)"],
        "url": "https://maandhan.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["Small/Marginal"],
        "crops": None
    },

    # 3. Irrigation schemes
    {
        "id": "pmksy-micro-irrigation",
        "name": "PMKSY - Per Drop More Crop (Micro Irrigation Subsidies)",
        "category": "Irrigation schemes",
        "department": "Department of Agricultural Engineering & Horticulture, Govt of Tamil Nadu",
        "purpose": "100% subsidy for Small & Marginal farmers and 75% subsidy for other category farmers for installing Drip and Sprinkler irrigation systems.",
        "deadline": "Open throughout the year (Subject to district physical allocation)",
        "method": "Online through Tamil Nadu Micro Irrigation Portal or Block Horticulture Officer",
        "documents": ["Aadhaar Card", "Land Ownership Documents (Patta, Chitta, FMB sketch)", "Water & Electricity certificate", "Soil & Water Test Report", "Bank Passbook", "Small/Marginal Farmer Certificate"],
        "url": "https://pmksy.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Gujarat", "Rajasthan", "Madhya Pradesh", "Uttar Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "tn-free-agri-power",
        "name": "Tamil Nadu Free Electricity Scheme for Agricultural Pumpsets",
        "category": "Irrigation schemes",
        "department": "TANGEDCO / Energy Department, Govt of Tamil Nadu",
        "purpose": "100% free electricity power supply for operational agricultural pumpsets and agricultural borewells of registered farming landholders.",
        "deadline": "Standing permanent state scheme",
        "method": "Apply at local TANGEDCO Section Office / Uzhavan App",
        "documents": ["Patta / Chitta", "VAO Certificate of agriculture land use", "Pumpset installation details", "Aadhaar Card"],
        "url": "https://www.tangedco.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "pm-kusum-solar-pump",
        "name": "PM-KUSUM Scheme (Solar Agriculture Pumpset Subsidies)",
        "category": "Irrigation schemes",
        "department": "Ministry of New and Renewable Energy (MNRE) / AED Tamil Nadu",
        "purpose": "Up to 70% subsidy (Central + State Govt) for standalone off-grid Solar Powered Agricultural Pumps (3HP to 10HP) and solarisation of existing grid-connected pumps.",
        "deadline": "Annual sanction window",
        "method": "Apply online at pmkusum.mnre.gov.in or Agricultural Engineering Department",
        "documents": ["Aadhaar Card", "Land Patta/Chitta", "Borewell / Open well water source certificate", "Bank Passbook"],
        "url": "https://pmkusum.mnre.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Gujarat", "Rajasthan", "Madhya Pradesh", "Uttar Pradesh", "Punjab", "Haryana"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 4. Crop insurance
    {
        "id": "pmfby-crop-insurance",
        "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "category": "Crop insurance",
        "department": "Ministry of Agriculture & Farmers Welfare, Govt of India",
        "purpose": "Comprehensive crop insurance coverage against non-preventable natural risks (drought, flood, unseasonal rainfall, pests, diseases) from pre-sowing to post-harvest at minimal premium (1.5% - 2%).",
        "deadline": "Cut-off dates notified every season (Kharif: July 31, Rabi: Nov 15/Dec 15)",
        "method": "Apply online at pmfby.gov.in, Commercial Banks, Primary Agricultural Co-op Societies (PACS), or CSC centres",
        "documents": ["Aadhaar Card", "Adangal / Sowing Certificate from VAO", "Land Record (Patta/Chitta)", "Bank Passbook", "Crop Sowing Declaration"],
        "url": "https://pmfby.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Gujarat", "Madhya Pradesh", "Rajasthan", "Haryana", "Odisha", "West Bengal", "Bihar"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "weather-based-crop-insurance",
        "name": "Restructured Weather Based Crop Insurance Scheme (RWBCIS)",
        "category": "Crop insurance",
        "department": "Department of Agriculture, Govt of India & State Agriculture Departments",
        "purpose": "Parametric weather index-based insurance covering adverse weather conditions like temperature deviations, unseasonal rainfall, high humidity, and frost.",
        "deadline": "Notified prior to start of crop risk period",
        "method": "Apply via Commercial Banks, Co-operative Banks, or PMFBY portal",
        "documents": ["Aadhaar Card", "Land Revenue Record", "Crop Cultivation Certificate", "Bank Account Details"],
        "url": "https://pmfby.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 5. Seeds/input assistance
    {
        "id": "certified-seed-distribution",
        "name": "Sub-Mission on Seeds and Planting Material (SMSP) & Certified Seed Subsidy",
        "category": "Seeds/input assistance",
        "department": "Department of Agriculture, Tamil Nadu / Seeds Division, GoI",
        "purpose": "50% subsidy on foundation and certified seeds of Paddy, Pulses, Millets, Oilseeds, and green manure crops distributed through AECs.",
        "deadline": "Available at the beginning of each cropping season",
        "method": "Agricultural Extension Centers (AEC) / Uzhavan App Booking",
        "documents": ["Uzhavan App Registration / Farmer ID", "Aadhaar Card", "Land Area Declaration"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Madhya Pradesh", "Punjab", "Haryana"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": ["Paddy", "Wheat", "Maize", "Groundnut", "Black Gram", "Chickpea", "Millets"]
    },
    {
        "id": "fertilizer-subsidy-dbt",
        "name": "Direct Benefit Transfer (DBT) in Fertilizer Subsidy Scheme",
        "category": "Seeds/input assistance",
        "department": "Department of Fertilizers, Ministry of Chemicals & Fertilizers, Govt of India",
        "purpose": "Subsidized supply of Urea, DAP, MOP, and Complex NPK fertilizers to farmers through PoS biometric machines at approved retailer outlets.",
        "deadline": "Continuous supply throughout the year",
        "method": "Purchase at licensed fertilizer retail shops with Aadhaar authentication on PoS device",
        "documents": ["Aadhaar Card / Kisan Credit Card"],
        "url": "https://fert.nic.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 6. Farm equipment subsidies
    {
        "id": "smam-farm-mechanization",
        "name": "Sub-Mission on Agricultural Mechanization (SMAM) - Farm Machinery Subsidy",
        "category": "Farm equipment subsidies",
        "department": "Agricultural Engineering Department (AED), Govt of Tamil Nadu",
        "purpose": "40% to 50% capital subsidy (up to 50% for SC/ST/Women/Small farmers) for purchasing Tractors, Power Tillers, Paddy Transplanters, Rotavators, Power Weeders, and Drones.",
        "deadline": "Annual target registration on Agricoop/AED portal",
        "method": "Apply online via agrimachinery.nic.in or Agricultural Engineering Department portal",
        "documents": ["Aadhaar Card", "Land Patta/Chitta", "Small/Marginal/Community Certificate", "Bank Passbook", "Dealer Quotation"],
        "url": "https://agrimachinery.nic.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Gujarat", "Madhya Pradesh", "Uttar Pradesh", "Punjab", "Haryana"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "custom-hiring-centres",
        "name": "Establishment of Custom Hiring Centres (CHC) for Agricultural Machinery",
        "category": "Farm equipment subsidies",
        "department": "Agricultural Engineering Department, Govt of Tamil Nadu",
        "purpose": "40% financial subsidy up to ₹10-25 Lakhs to Farmer Producer Organizations (FPOs) and Primary Agricultural Cooperative Societies for establishing machinery hiring hubs.",
        "deadline": "Project-based annual approval",
        "method": "Apply through Executive Engineer (AED) or agrimachinery.nic.in",
        "documents": ["Group/FPO Registration Certificate", "Member Farmers Land Details", "Bank Account Details", "Machinery Requirement Proposal"],
        "url": "https://agrimachinery.nic.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 7. Soil/land improvement
    {
        "id": "soil-health-card-scheme",
        "name": "National Soil Health Card Scheme & Soil Improvement Support",
        "category": "Soil/land improvement",
        "department": "Department of Agriculture & Farmers Welfare, Ministry of Agriculture, GoI",
        "purpose": "Free laboratory soil testing and distribution of Soil Health Cards with customized dosage recommendations for chemical fertilizers, micronutrients, biofertilizers, and organic manure.",
        "deadline": "Ongoing periodic soil testing cycles",
        "method": "Soil sample collection by Village Agriculture Assistant or submit directly at District Soil Testing Lab",
        "documents": ["Aadhaar Card", "Land Survey Number & Village Details", "Mobile Number"],
        "url": "https://soilhealth.dac.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "nmsa-rainfed-development",
        "name": "National Mission for Sustainable Agriculture (NMSA) - Rainfed Area Development",
        "category": "Soil/land improvement",
        "department": "Department of Agriculture, Govt of Tamil Nadu / GoI",
        "purpose": "Financial assistance for integrated farming systems (IFS), soil moisture conservation, green manuring, vermicompost pits, and farm ponds.",
        "deadline": "Annual state plan implementation",
        "method": "Block Assistant Director of Agriculture (ADA) / Uzhavan App",
        "documents": ["Aadhaar Card", "Land Patta/Chitta", "Bank Passbook", "Farming Activity Plan"],
        "url": "https://nmsa.dac.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Madhya Pradesh", "Rajasthan"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 8. Organic/natural farming
    {
        "id": "pkvy-organic-farming",
        "name": "Paramparagat Krishi Vikas Yojana (PKVY) - Organic Cluster Scheme",
        "category": "Organic/natural farming",
        "department": "National Centre of Organic and Natural Farming / TNOCD",
        "purpose": "Financial assistance of ₹50,000 per hectare for 3 years for organic cluster formation, bio-fertilizer procurement, vermicompost units, PGS-India certification, and market branding.",
        "deadline": "Cluster enrollment cycles",
        "method": "Join certified farmer clusters through Block Agriculture Officer or apply via PGS-India Portal",
        "documents": ["Aadhaar Card", "Land Record Documents", "Bank Account Details", "Organic Farming Commitment Undertaking"],
        "url": "https://pgsindia-ncof.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Madhya Pradesh", "Gujarat", "Rajasthan", "Odisha"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "tn-organic-farming-mission",
        "name": "Tamil Nadu Organic Farming Mission (TNOFM)",
        "category": "Organic/natural farming",
        "department": "Department of Agriculture and Farmers Welfare, Govt of Tamil Nadu",
        "purpose": "Special state subsidy for setting up on-farm organic input production units (Jeevamrutham, Panchakavya, Vermicompost) and organic certification cost assistance.",
        "deadline": "Open for current agricultural budget year",
        "method": "Tamil Nadu Organic Certification Department (TNOCD) / Block Agriculture Extension Centre",
        "documents": ["Aadhaar Card", "Land Chitta/Adangal", "Organic Conversion Plan", "Bank Passbook"],
        "url": "https://www.tnagrisnet.tn.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },

    # 9. Other agriculture subsidies
    {
        "id": "kisan-credit-card-iss",
        "name": "Kisan Credit Card (KCC) Scheme with Modified Interest Subvention (MISS)",
        "category": "Other agriculture subsidies",
        "department": "NABARD & Reserve Bank of India / Ministry of Agriculture, GoI",
        "purpose": "Short-term crop production credit up to ₹3 Lakhs at a concessional interest rate of 4% per annum for prompt repayment, with collateral-free facility up to ₹1.6 Lakhs.",
        "deadline": "Open throughout the year at all Commercial, Regional Rural and Co-operative Banks",
        "method": "Submit 1-page KCC application form at nearest bank branch or Primary Agricultural Credit Society (PACS)",
        "documents": ["Aadhaar Card", "PAN Card / Form 60", "Land Patta/Chitta & Adangal crop cultivation proof", "Passport size photos"],
        "url": "https://www.nabard.org",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "West Bengal", "Bihar", "Odisha", "Gujarat", "Rajasthan", "Madhya Pradesh"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    },
    {
        "id": "agriculture-infrastructure-fund",
        "name": "Agriculture Infrastructure Fund (AIF) - Post Harvest Management",
        "category": "Other agriculture subsidies",
        "department": "Department of Agriculture & Farmers Welfare, Ministry of Agriculture, GoI",
        "purpose": "Medium-long term debt financing with 3% per annum interest subvention up to ₹2 Crores for creating post-harvest infrastructure (cold storages, warehouses, drying yards, sorting units).",
        "deadline": "Active scheme window through 2032-33",
        "method": "Online application directly through central AIF portal",
        "documents": ["Aadhaar & PAN", "Detailed Project Report (DPR)", "Land ownership / registered lease agreement", "Bank financial statements"],
        "url": "https://agriinfra.dac.gov.in",
        "countries": ["India"],
        "states": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana", "Gujarat", "Madhya Pradesh", "Rajasthan", "Bihar", "West Bengal", "Odisha"],
        "farmer_category": ["General", "Small/Marginal", "SC/ST", "Women"],
        "crops": None
    }
]

# -------------------------------------------------------------
# SCHEMES ELIGIBILITY EVALUATION ENGINE
# -------------------------------------------------------------

def check_eligibility(
    scheme,
    country,
    state,
    district,
    recommended_crop,
    land_area,
    farmer_category
):
    """Return scheme eligibility status and explanation."""

    # 1. COUNTRY CHECK
    allowed_countries = scheme.get("countries") or scheme.get("country")
    if allowed_countries:
        if isinstance(allowed_countries, str):
            allowed_countries = [allowed_countries]
        allowed_country_names = {
            str(value).strip().lower()
            for value in allowed_countries
            if value
        }
        if country and country.strip().lower() not in allowed_country_names:
            return ("ineligible", "This scheme is not available in your country.")

    # 2. STATE CHECK
    allowed_states = scheme.get("states") or scheme.get("state")
    if allowed_states:
        if isinstance(allowed_states, str):
            allowed_states = [allowed_states]
        allowed_state_names = {
            str(value).strip().lower()
            for value in allowed_states
            if value
        }
        if state and state.strip().lower() not in allowed_state_names:
            return ("ineligible", "This scheme is not available in your state.")

    # 3. FARMER CATEGORY CHECK
    required_category = scheme.get("farmer_category") or scheme.get("category_eligibility")
    if required_category:
        if isinstance(required_category, str):
            required_category = [required_category]
        allowed_categories = {
            str(value).strip().lower()
            for value in required_category
            if value
        }
        current_category = str(farmer_category or "").strip().lower()
        if current_category and current_category not in allowed_categories:
            return ("ineligible", "Your farmer category does not match this scheme.")

    # 4. CROP CHECK
    required_crop = scheme.get("crop") or scheme.get("crops")
    if required_crop and recommended_crop:
        if isinstance(required_crop, str):
            required_crop = [required_crop]
        allowed_crops = {
            str(value).strip().lower()
            for value in required_crop
            if value
        }
        current_crop = str(recommended_crop).strip().lower()
        if current_crop not in allowed_crops:
            return ("ineligible", "This scheme does not support the recommended crop.")

    return ("eligible", "You meet the available eligibility criteria.")

# -------------------------------------------------------------
# CORE APPLICATION ROUTES
# -------------------------------------------------------------

@app.route("/")
def index():
    """Home landing page with project introduction and features."""
    return render_template("index.html")

@app.route("/about")
def about():
    """About page highlighting ML Decision Tree explainability and project specs."""
    return render_template("about.html")

@app.route("/android-splash")
def android_splash():
    """Native Android app splash screen."""
    return render_template("android_splash.html")

# -------------------------------------------------------------
# AUTHENTICATION & REGISTRATION OTP FLOW
# -------------------------------------------------------------

@app.route("/register", methods=["GET", "POST"])
def register():
    """Farmer registration initiation with 6-digit OTP dispatch."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        mobile = request.form.get("mobile", "").strip()
        email = request.form.get("email", "").strip().lower()
        farm_location = request.form.get("farm_location", "").strip()
        land_area = request.form.get("land_area", "1.0").strip()
        land_unit = request.form.get("land_unit", "Acres").strip()
        preferred_soil = request.form.get("preferred_soil", "Loamy").strip()
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if not name or not mobile or not email or not password:
            flash("Please fill in all required registration fields.", "danger")
            return render_template("register.html")

        if password != confirm_password:
            flash("Passwords do not match. Please re-enter your password.", "danger")
            return render_template("register.html")

        if len(password) < 6:
            flash("Password must be at least 6 characters in length.", "danger")
            return render_template("register.html")

        # Clean up any unverified duplicate user with the same email
        delete_unverified_user(email)

        # Create user record with is_verified = 0
        user_id, err = create_user(
            name=name,
            mobile=mobile,
            email=email,
            password=password,
            farm_location=farm_location,
            land_area=land_area,
            land_unit=land_unit,
            preferred_soil=preferred_soil,
            is_verified=0
        )

        if err:
            flash(err, "danger")
            return render_template("register.html")

        # Generate ONE 6-digit OTP (source of truth)
        otp_code = f"{random.randint(100000, 999999)}"
        otp_hash = generate_password_hash(otp_code)
        expiry = time.time() + 300  # 5 minutes validity

        update_user_otp(user_id, otp_hash, expiry, time.time())

        # Store pending session state for OTP screen
        session["pending_email"] = email
        session["pending_user_id"] = user_id
        session["pending_name"] = name
        session["otp_sent_at"] = time.time()

        # Send OTP via EmailJS
        origin_url = request.host_url
        email_sent, send_err = send_otp_email(email, otp_code, origin_url=origin_url)

        if not email_sent:
            flash("We couldn't send the verification OTP to your email. Please check your email address and try again.", "danger")
            return render_template("register.html")

        flash("A 6-digit verification OTP has been sent to your email. Please enter it to complete registration.", "success")
        return redirect(url_for("verify_otp"))

    return render_template("register.html")

@app.route("/verify-otp", methods=["GET", "POST"])
def verify_otp():
    """Verify the 6-digit OTP sent to the farmer's email."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    pending_email = session.get("pending_email")
    if not pending_email:
        flash("Registration session expired or not found. Please register again.", "warning")
        return redirect(url_for("register"))

    # Calculate resend countdown
    otp_sent_at = session.get("otp_sent_at", time.time())
    elapsed = int(time.time() - otp_sent_at)
    resend_in = max(0, 45 - elapsed)

    if request.method == "POST":
        entered_otp = request.form.get("otp", "").strip()

        if not entered_otp or len(entered_otp) != 6 or not entered_otp.isdigit():
            flash("Please enter the complete 6-digit OTP.", "danger")
            return render_template("verify_otp.html", resend_in=resend_in, email=pending_email)

        success, result = verify_user_otp(pending_email, entered_otp)

        if success:
            user_id = result
            user = get_user_by_id(user_id)
            if user:
                session["user_id"] = user["id"]
                session["user_name"] = user["name"]
                session["user_email"] = user["email"]

            # Clear temporary session data
            session.pop("pending_email", None)
            session.pop("pending_user_id", None)
            session.pop("pending_name", None)
            session.pop("otp_sent_at", None)

            flash("Email verified successfully! Welcome to CROPWISE AI.", "success")
            return redirect(url_for("dashboard"))
        else:
            if "expired" in str(result).lower():
                flash("Your OTP has expired. Please request a new OTP.", "danger")
            elif "too many" in str(result).lower():
                flash("Too many invalid attempts. Please request a new OTP.", "danger")
            else:
                flash("Incorrect OTP. Please try again.", "danger")
            return render_template("verify_otp.html", resend_in=resend_in, email=pending_email)

    return render_template("verify_otp.html", resend_in=resend_in, email=pending_email)

@app.route("/resend-otp")
def resend_otp():
    """Resend a new 6-digit OTP to the farmer's pending email."""
    pending_email = session.get("pending_email")
    pending_user_id = session.get("pending_user_id")
    pending_name = session.get("pending_name")

    if not pending_email or not pending_user_id:
        flash("Session expired. Please register again.", "warning")
        return redirect(url_for("register"))

    otp_sent_at = session.get("otp_sent_at", 0)
    if time.time() - otp_sent_at < 30:
        flash("Please wait before requesting another OTP.", "warning")
        return redirect(url_for("verify_otp"))

    # Generate NEW 6-digit OTP (invalidates previous OTP)
    otp_code = f"{random.randint(100000, 999999)}"
    otp_hash = generate_password_hash(otp_code)
    expiry = time.time() + 300

    update_user_otp(pending_user_id, otp_hash, expiry, time.time())
    session["otp_sent_at"] = time.time()

    origin_url = request.host_url
    email_sent, send_err = send_otp_email(pending_email, otp_code, origin_url=origin_url)

    if not email_sent:
        flash("We couldn't send the new OTP email. Please try again in a moment.", "danger")
        return redirect(url_for("verify_otp"))

    flash("A new 6-digit OTP has been sent to your email.", "success")
    return redirect(url_for("verify_otp"))

@app.route("/login", methods=["GET", "POST"])
def login():
    """Farmer login handler with identifier and password."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    if request.method == "POST":
        identifier = request.form.get("identifier", "").strip()
        password = request.form.get("password", "")

        if not identifier or not password:
            flash("Please enter both mobile/email and password.", "danger")
            return render_template("login.html")

        user = authenticate_user(identifier, password)

        if user:
            # Check verification status
            if not user.get("is_verified", 1):
                session["pending_email"] = user["email"]
                session["pending_user_id"] = user["id"]
                session["pending_name"] = user["name"]
                session["otp_sent_at"] = time.time()

                otp_code = f"{random.randint(100000, 999999)}"
                otp_hash = generate_password_hash(otp_code)
                update_user_otp(user["id"], otp_hash, time.time() + 300, time.time())

                origin_url = request.host_url
                send_otp_email(user["email"], otp_code, origin_url=origin_url)

                flash("Please verify your email address before logging in. A new 6-digit OTP has been sent to your email.", "warning")
                return redirect(url_for("verify_otp"))

            session["user_id"] = user["id"]
            session["user_name"] = user["name"]
            session["user_email"] = user["email"]
            flash(f"Welcome back, {user['name']}!", "success")
            return redirect(url_for("dashboard"))
        else:
            flash("Invalid mobile number/email or password. Please try again.", "danger")
            return render_template("login.html")

    return render_template("login.html")

@app.route("/logout")
def logout():
    """Farmer logout and session termination."""
    session.clear()
    flash("You have been logged out successfully.", "info")
    return redirect(url_for("login"))

@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    """Handle password reset request by validating registered email and sending 6-digit OTP."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()

        if not email:
            flash("Please enter your registered email address.", "danger")
            return render_template("forgot_password.html")

        user = get_user_by_email(email)
        if not user:
            flash("No account is registered with this email address. Please check your email or register.", "danger")
            return render_template("forgot_password.html", entered_email=email)

        # Generate ONE 6-digit OTP
        otp_code = f"{random.randint(100000, 999999)}"
        otp_hash = generate_password_hash(otp_code)
        expiry = time.time() + 300  # 5 minutes validity

        update_user_otp(user["id"], otp_hash, expiry, time.time())

        # Store reset session state
        session["reset_email"] = user["email"]
        session["reset_user_id"] = user["id"]
        session["reset_name"] = user.get("name", "")
        session["reset_otp_sent_at"] = time.time()
        session["reset_otp_verified"] = False

        # Send OTP via EmailJS
        origin_url = request.host_url
        email_sent, send_err = send_otp_email(user["email"], otp_code, origin_url=origin_url)

        if not email_sent:
            flash("We couldn't send the reset OTP to your email. Please try again in a moment.", "danger")
            return render_template("forgot_password.html", entered_email=email)

        flash("A 6-digit password reset OTP has been sent to your email. Please enter it below.", "success")
        return redirect(url_for("reset_password_verify"))

    return render_template("forgot_password.html")

@app.route("/reset-password-verify", methods=["GET", "POST"])
def reset_password_verify():
    """Verify OTP sent for password reset."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    reset_email = session.get("reset_email")
    reset_user_id = session.get("reset_user_id")
    if not reset_email or not reset_user_id:
        flash("Password reset session expired or not found. Please start again.", "warning")
        return redirect(url_for("forgot_password"))

    # Calculate resend countdown
    otp_sent_at = session.get("reset_otp_sent_at", time.time())
    elapsed = int(time.time() - otp_sent_at)
    resend_in = max(0, 45 - elapsed)

    if request.method == "POST":
        entered_otp = request.form.get("otp", "").strip()

        if not entered_otp or len(entered_otp) != 6 or not entered_otp.isdigit():
            flash("Please enter the complete 6-digit OTP.", "danger")
            return render_template("reset_password_verify.html", resend_in=resend_in, email=reset_email)

        success, result = verify_reset_otp(reset_email, entered_otp)

        if success:
            session["reset_otp_verified"] = True
            flash("OTP verified successfully! Please set your new password.", "success")
            return redirect(url_for("reset_password"))
        else:
            if "expired" in str(result).lower():
                flash("Your OTP has expired. Please request a new OTP.", "danger")
            elif "too many" in str(result).lower():
                flash("Too many invalid attempts. Please request a new OTP.", "danger")
            else:
                flash("Incorrect OTP. Please try again.", "danger")
            return render_template("reset_password_verify.html", resend_in=resend_in, email=reset_email)

    return render_template("reset_password_verify.html", resend_in=resend_in, email=reset_email)

@app.route("/resend-reset-otp")
def resend_reset_otp():
    """Resend a new 6-digit OTP to the farmer's reset email."""
    reset_email = session.get("reset_email")
    reset_user_id = session.get("reset_user_id")

    if not reset_email or not reset_user_id:
        flash("Password reset session expired. Please start again.", "warning")
        return redirect(url_for("forgot_password"))

    otp_sent_at = session.get("reset_otp_sent_at", 0)
    if time.time() - otp_sent_at < 30:
        flash("Please wait before requesting another OTP.", "warning")
        return redirect(url_for("reset_password_verify"))

    # Generate NEW 6-digit OTP
    otp_code = f"{random.randint(100000, 999999)}"
    otp_hash = generate_password_hash(otp_code)
    expiry = time.time() + 300

    update_user_otp(reset_user_id, otp_hash, expiry, time.time())
    session["reset_otp_sent_at"] = time.time()

    origin_url = request.host_url
    email_sent, send_err = send_otp_email(reset_email, otp_code, origin_url=origin_url)

    if not email_sent:
        flash("We couldn't send the new OTP email. Please try again in a moment.", "danger")
        return redirect(url_for("reset_password_verify"))

    flash("A new 6-digit OTP has been sent to your email.", "success")
    return redirect(url_for("reset_password_verify"))

@app.route("/reset-password", methods=["GET", "POST"])
def reset_password():
    """Allow user to enter New Password and Confirm Password after OTP verification."""
    if session.get("user_id"):
        return redirect(url_for("dashboard"))

    reset_user_id = session.get("reset_user_id")
    reset_email = session.get("reset_email")
    reset_verified = session.get("reset_otp_verified")

    if not reset_user_id or not reset_email or not reset_verified:
        flash("Please verify your OTP before resetting password.", "warning")
        return redirect(url_for("forgot_password"))

    if request.method == "POST":
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if not password or not confirm_password:
            flash("Please enter both password and confirm password.", "danger")
            return render_template("reset_password.html")

        if password != confirm_password:
            flash("Passwords do not match. Please re-enter your password.", "danger")
            return render_template("reset_password.html")

        if len(password) < 6:
            flash("Password must be at least 6 characters in length.", "danger")
            return render_template("reset_password.html")

        success = update_user_password(reset_user_id, password)

        # Clear reset session tokens
        session.pop("reset_email", None)
        session.pop("reset_user_id", None)
        session.pop("reset_name", None)
        session.pop("reset_otp_sent_at", None)
        session.pop("reset_otp_verified", None)

        if success:
            flash("Password reset successfully! You can now log in with your new password.", "success")
            return redirect(url_for("login"))
        else:
            flash("Failed to update password. Please try again.", "danger")
            return redirect(url_for("forgot_password"))

    return render_template("reset_password.html")

# -------------------------------------------------------------
# DASHBOARD & PROFILE
# -------------------------------------------------------------

@app.route("/dashboard")
@login_required
def dashboard():
    """Farmer dashboard with quick module actions, metrics, and latest records."""
    user_id = session["user_id"]
    user = get_user_by_id(user_id)
    if not user:
        session.clear()
        flash("Session expired. Please log in again.", "warning")
        return redirect(url_for("login"))

    history = get_recommendation_history(user_id, limit=1)
    last_rec = history[0] if history else None
    expense_summary = get_expense_summary(user_id)

    return render_template(
        "dashboard.html",
        user=user,
        last_rec=last_rec,
        expense_summary=expense_summary
    )

@app.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    """Farmer profile viewer and settings updater."""
    user_id = session["user_id"]
    user = get_user_by_id(user_id)
    if not user:
        flash("User information not found.", "danger")
        return redirect(url_for("dashboard"))

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        mobile = request.form.get("mobile", "").strip()
        email = request.form.get("email", "").strip().lower()
        farm_location = request.form.get("farm_location", "").strip()
        land_area = float(request.form.get("land_area", 1.0))
        land_unit = request.form.get("land_unit", "Acres")
        preferred_soil = request.form.get("preferred_soil", "Loamy")
        avatar = user.get("avatar", "farmer1")

        success, err = update_user_profile(
            user_id,
            name,
            mobile,
            email,
            farm_location,
            land_area,
            land_unit,
            preferred_soil,
            avatar
        )

        if success:
            session["user_name"] = name
            session["user_email"] = email
            flash("Farm profile updated successfully.", "success")
            return redirect(url_for("profile"))
        else:
            flash(err or "Failed to update profile.", "danger")
            return redirect(url_for("profile"))

    return render_template("profile.html", user=user)

# -------------------------------------------------------------
# CROP RECOMMENDATION (DECISION TREE ML ENGINE)
# -------------------------------------------------------------

@app.route("/recommend", methods=["GET", "POST"])
@login_required
def recommend():
    """Crop recommendation input form and Decision Tree inference engine."""
    user_id = session["user_id"]
    user = get_user_by_id(user_id)

    soil_types = ['Alluvial', 'Black', 'Clay', 'Laterite', 'Loamy', 'Red', 'Sandy']

    if request.method == "POST":
        soil_type = request.form.get("soil_type", "Loamy")
        ph = float(request.form.get("ph", 6.5))
        temperature = float(request.form.get("temperature", 25.0))
        humidity = float(request.form.get("humidity", 70.0))
        rainfall = float(request.form.get("rainfall", 1000.0))

        pred_crop = "Paddy"
        alt_crops = []

        if dt_model is not None and soil_encoder is not None and crop_encoder is not None:
            try:
                s_enc_input = "Clayey" if (soil_type == "Clay" and "Clayey" in soil_encoder.classes_ and "Clay" not in soil_encoder.classes_) else soil_type
                s_enc = soil_encoder.transform([s_enc_input])[0]
                input_df = pd.DataFrame([{
                    'Soil_Type_Encoded': s_enc,
                    'pH': ph,
                    'Temperature': temperature,
                    'Humidity': humidity,
                    'Rainfall': rainfall
                }])

                pred_idx = dt_model.predict(input_df)[0]
                pred_crop = crop_encoder.inverse_transform([pred_idx])[0]

                # Extract alternatives from probability distribution
                probs = dt_model.predict_proba(input_df)[0]
                top_indices = np.argsort(probs)[::-1]
                alt_crops = [
                    crop_encoder.classes_[i]
                    for i in top_indices
                    if probs[i] > 0 and crop_encoder.classes_[i] != pred_crop
                ][:3]
            except Exception as e:
                print(f"[WARN] Decision Tree inference exception: {e}")

        # Fallback alternatives if probability distribution yields fewer than 2
        if len(alt_crops) < 2:
            all_available = [c for c in crop_database.keys() if c != pred_crop]
            for candidate in all_available:
                c_info = crop_database.get(candidate, {})
                if soil_type in c_info.get("ideal_soil", []) or (soil_type == "Clay" and "Clayey" in c_info.get("ideal_soil", [])):
                    if candidate not in alt_crops:
                        alt_crops.append(candidate)
                if len(alt_crops) >= 3:
                    break
            if len(alt_crops) < 2:
                for fallback_crop in ["Wheat", "Maize", "Groundnut", "Banana"]:
                    if fallback_crop != pred_crop and fallback_crop not in alt_crops:
                        alt_crops.append(fallback_crop)
                    if len(alt_crops) >= 3:
                        break

        # Agronomic explainability reasoning
        crop_info = crop_database.get(pred_crop, {})
        ideal_ph = crop_info.get("ph_range", "6.0 - 7.5")
        ideal_temp = crop_info.get("temp_range", "20°C - 35°C")

        decision_notes = (
            f"Decision Tree Rule Branch: Soil type '{soil_type}', pH {ph:.1f} (Ideal: {ideal_ph}), "
            f"Temperature {temperature:.1f}°C (Ideal: {ideal_temp}), Humidity {humidity:.1f}%, "
            f"and Annual Rainfall {rainfall:.1f}mm align precisely with the optimal agronomic growth profile of {pred_crop}."
        )

        rec_id = save_recommendation(
            user_id=user_id,
            soil_type=soil_type,
            ph=ph,
            temperature=temperature,
            humidity=humidity,
            rainfall=rainfall,
            recommended_crop=pred_crop,
            alternative_crops=alt_crops,
            decision_notes=decision_notes,
            variety="Standard"
        )

        return redirect(url_for("result", rec_id=rec_id))

    return render_template(
        "recommend.html",
        soil_types=soil_types,
        current_user=user
    )

@app.route("/result/<int:rec_id>")
@login_required
def result(rec_id):
    """Display comprehensive recommendation result with growth details and alternatives."""
    user_id = session["user_id"]
    rec = get_recommendation_by_id(rec_id, user_id)
    if not rec:
        flash("Recommendation record not found.", "danger")
        return redirect(url_for("dashboard"))

    crop_name = rec["recommended_crop"]
    crop_info = crop_database.get(crop_name, {})

    alt_crops_data = []
    for alt in rec.get("alternative_crops_list", []):
        if alt in crop_database:
            alt_crops_data.append(crop_database[alt])
        else:
            alt_crops_data.append({
                "name": alt,
                "tamil_name": "",
                "duration_days": "100 - 120 Days"
            })

    return render_template(
        "result.html",
        rec=rec,
        crop_name=crop_name,
        crop_info=crop_info,
        alt_crops_data=alt_crops_data
    )

# -------------------------------------------------------------
# RECOMMENDATION HISTORY
# -------------------------------------------------------------

@app.route("/history")
@login_required
def history():
    """Farmer recommendation history log."""
    user_id = session["user_id"]
    hist_records = get_recommendation_history(user_id, limit=50)
    return render_template("history.html", history=hist_records)

@app.route("/history/delete/<int:rec_id>", methods=["POST"])
@login_required
def delete_history_item(rec_id):
    """Delete a past recommendation log entry."""
    user_id = session["user_id"]
    delete_recommendation(rec_id, user_id)
    flash("Recommendation log entry deleted successfully.", "success")
    return redirect(url_for("history"))

# -------------------------------------------------------------
# FARM EXPENSES & FIELD NOTES
# -------------------------------------------------------------

@app.route("/expenses")
@login_required
def expenses():
    """Farm expenses ledger and field notebook."""
    user_id = session["user_id"]
    user_exp = get_user_expenses(user_id)
    summary = get_expense_summary(user_id)
    notes = get_user_notes(user_id)
    reminders = get_user_reminders(user_id)
    now = datetime.datetime.now()
    for reminder in reminders:
        reminder_at = datetime.datetime.strptime(
            f"{reminder['reminder_date']} {reminder.get('reminder_time') or '00:00'}",
            "%Y-%m-%d %H:%M"
        )
        if reminder["is_completed"]:
            reminder["status"] = "completed"
        elif reminder_at < now:
            reminder["status"] = "overdue"
        else:
            reminder["status"] = "upcoming"
    current_date = datetime.date.today().isoformat()
    current_month_prefix = current_date[:7]
    current_month_name = now.strftime("%B %Y")
    month_expenses = [e for e in user_exp if str(e.get("expense_date", "")).startswith(current_month_prefix)]
    month_total = sum(float(e.get("amount", 0.0)) for e in month_expenses)
    month_by_category = {}
    for e in month_expenses:
        cat = e.get("category", "Other")
        month_by_category[cat] = month_by_category.get(cat, 0.0) + float(e.get("amount", 0.0))

    return render_template(
        "expenses.html",
        expenses=user_exp,
        summary=summary,
        notes=notes,
        reminders=reminders,
        current_date=current_date,
        current_month_name=current_month_name,
        month_expenses=month_expenses,
        month_total=month_total,
        month_by_category=month_by_category
    )

@app.route("/expenses/add", methods=["POST"])
@login_required
def add_new_expense():
    """Add a new farm expenditure entry."""
    user_id = session["user_id"]
    expense_date = request.form.get("expense_date") or datetime.date.today().isoformat()
    category = request.form.get("category", "Other")
    try:
        amount = float(request.form.get("amount", 0.0))
    except (ValueError, TypeError):
        amount = 0.0
    description = request.form.get("description", "").strip()

    if amount > 0:
        add_expense(user_id, expense_date, category, amount, description)
        flash("Farm expense logged successfully.", "success")
    else:
        flash("Please enter a valid expense amount greater than zero.", "warning")

    return redirect(url_for("expenses"))

@app.route("/expenses/delete/<int:exp_id>", methods=["POST"])
@login_required
def delete_user_expense(exp_id):
    """Delete an expense record."""
    user_id = session["user_id"]
    delete_expense(exp_id, user_id)
    flash("Expense record deleted.", "success")
    return redirect(url_for("expenses"))

@app.route("/notes/add", methods=["POST"])
@login_required
def add_new_note():
    """Add a new agricultural field note or observation."""
    user_id = session["user_id"]
    title = request.form.get("title", "").strip()
    content = request.form.get("content", "").strip()
    tag = request.form.get("tag", "General").strip()

    if title and content:
        add_note(user_id, title, content, tag)
        flash("Field note saved successfully.", "success")
    else:
        flash("Please provide both a title and note content.", "warning")

    return redirect(url_for("expenses"))

@app.route("/notes/delete/<int:note_id>", methods=["POST"])
@login_required
def delete_user_note(note_id):
    """Delete a saved field note."""
    user_id = session["user_id"]
    delete_note(note_id, user_id)
    flash("Field note deleted.", "success")
    return redirect(url_for("expenses"))

@app.route("/reminders/add", methods=["POST"])
@login_required
def add_new_reminder():
    """Add a scheduled farm reminder without changing field notes."""
    user_id = session["user_id"]
    reminder_date = request.form.get("reminder_date", "").strip()
    reminder_time = request.form.get("reminder_time", "").strip()
    title = request.form.get("reminder_title", "").strip()
    description = request.form.get("reminder_description", "").strip()

    try:
        datetime.datetime.strptime(f"{reminder_date} {reminder_time}", "%Y-%m-%d %H:%M")
    except ValueError:
        flash("Please provide a valid reminder date and time.", "warning")
        return redirect(url_for("expenses"))

    if title and description:
        add_reminder(user_id, title, reminder_date, reminder_time, description)
        flash("Farm reminder saved successfully.", "success")
    else:
        flash("Please provide a reminder title and description.", "warning")

    return redirect(url_for("expenses"))

@app.route("/reminders/toggle/<int:reminder_id>", methods=["POST"])
@login_required
def toggle_user_reminder(reminder_id):
    toggle_reminder(reminder_id, session["user_id"])
    return redirect(url_for("expenses"))

@app.route("/reminders/delete/<int:reminder_id>", methods=["POST"])
@login_required
def delete_user_reminder(reminder_id):
    delete_reminder(reminder_id, session["user_id"])
    flash("Farm reminder deleted.", "success")
    return redirect(url_for("expenses"))

# -------------------------------------------------------------
# DECISION-SUPPORT MODULES
# -------------------------------------------------------------

@app.route("/alternatives")
def alternatives():
    """Alternative crops explorer based on primary crop suitability."""
    crop_name = request.args.get("crop", "Paddy").strip()
    if crop_name not in crop_database:
        crop_name = "Paddy"

    primary_crop = crop_database.get(crop_name)

    # Find secondary candidates
    alternatives_list = []
    for c_name, c_data in crop_database.items():
        if c_name != crop_name:
            # Match if they share ideal soil or similar temperature category
            if any(s in primary_crop.get("ideal_soil", []) for s in c_data.get("ideal_soil", [])):
                alternatives_list.append(c_data)
        if len(alternatives_list) >= 4:
            break

    if len(alternatives_list) < 3:
        for c_name, c_data in crop_database.items():
            if c_name != crop_name and c_data not in alternatives_list:
                alternatives_list.append(c_data)
            if len(alternatives_list) >= 3:
                break

    return render_template(
        "alternatives.html",
        primary_crop=primary_crop,
        alternatives=alternatives_list
    )

@app.route("/duration")
def duration():
    """Crop growth duration timeline and 4-phase lifecycle."""
    crop_name = request.args.get("crop", "Paddy").strip()
    if crop_name not in crop_database:
        crop_name = "Paddy"

    crop_data = crop_database.get(crop_name)
    all_crops = list(crop_database.keys())

    return render_template(
        "duration.html",
        crop=crop_data,
        all_crops=all_crops
    )

@app.route("/comparison")
def comparison():
    """Interactive multi-crop agronomic comparison matrix."""
    selected_crops = request.args.getlist("crops")
    if not selected_crops:
        selected_crops = ["Paddy", "Wheat", "Maize", "Cotton", "Groundnut"]

    compared_crops = [
        crop_database[c]
        for c in selected_crops
        if c in crop_database
    ]

    if not compared_crops:
        compared_crops = [
            crop_database[c]
            for c in ["Paddy", "Wheat", "Maize", "Cotton"]
            if c in crop_database
        ]

    return render_template(
        "comparison.html",
        compared_crops=compared_crops,
        all_crops=crop_database
    )

@app.route("/budget")
def budget():
    """Farm cultivation budget calculator scaled to land area."""
    crop_name = request.args.get("crop", "Paddy").strip()
    if crop_name not in crop_database:
        crop_name = "Paddy"

    crop_data = crop_database.get(crop_name)
    all_crops = list(crop_database.keys())

    user = None
    if session.get("user_id"):
        user = get_user_by_id(session["user_id"])

    return render_template(
        "budget.html",
        crop=crop_data,
        all_crops=all_crops,
        user=user
    )

@app.route("/calendar")
def calendar():
    """Month-by-month agricultural operations calendar."""
    crop_name = request.args.get("crop", "Paddy").strip()
    if crop_name not in crop_database:
        crop_name = "Paddy"

    crop_data = crop_database.get(crop_name)

    return render_template(
        "calendar.html",
        crop=crop_data,
        all_crops=crop_database
    )

@app.route("/water")
def water():
    """Water requirement and irrigation methods advisory."""
    crop_name = request.args.get("crop", "Paddy").strip()
    if crop_name not in crop_database:
        crop_name = "Paddy"

    crop_data = crop_database.get(crop_name)

    user = None
    if session.get("user_id"):
        user = get_user_by_id(session["user_id"])

    return render_template(
        "water.html",
        crop=crop_data,
        all_crops=crop_database,
        user=user
    )

@app.route("/report/<int:rec_id>")
@login_required
def print_report(rec_id):
    """Printable official advisory report for farmer records & demonstration."""
    user_id = session["user_id"]
    rec = get_recommendation_by_id(rec_id, user_id)
    if not rec:
        flash("Recommendation record not found.", "danger")
        return redirect(url_for("dashboard"))

    user = get_user_by_id(user_id)
    crop_name = rec["recommended_crop"]
    crop_data = crop_database.get(crop_name, {})

    cost_per_acre = crop_data.get("cost_per_acre", {}).get("total_estimate", 25000) if crop_data else 25000
    land_area = float(user.get("land_area", 1.0)) if user else 1.0
    total_budget = land_area * cost_per_acre

    return render_template(
        "print_report.html",
        rec=rec,
        user=user,
        crop=crop_data,
        total_budget=total_budget
    )

# -------------------------------------------------------------
# GOVERNMENT SCHEMES & SUBSIDIES
# -------------------------------------------------------------

@app.route("/schemes", methods=["GET", "POST"])
@login_required
def schemes():
    """Government Schemes discovery and customized eligibility engine."""
    user_id = session["user_id"]
    user = get_user_by_id(user_id)

    if not user:
        flash("User information not found.", "danger")
        return redirect(url_for("dashboard"))

    # Get latest recommended crop
    history = get_recommendation_history(user_id, limit=1)
    recommended_crop = None
    if history:
        recommended_crop = history[0].get("recommended_crop")

    # Defaults
    country = "India"
    state = "Tamil Nadu"
    district = ""
    land_area = str(user.get("land_area") or "1.0")
    farmer_category = "General"

    # Derive location from profile
    location = str(user.get("farm_location") or "").strip()
    if location:
        parts = [p.strip() for p in location.split(",") if p.strip()]
        if parts:
            district = parts[0]
        location_lower = location.lower()
        if "tamil" in location_lower or "nadu" in location_lower:
            state = "Tamil Nadu"

    # POST - update criteria
    if request.method == "POST":
        country = request.form.get("country", "").strip() or "India"
        state = request.form.get("state", "").strip() or "Tamil Nadu"
        district = request.form.get("district", "").strip()
        land_area = request.form.get("land_area", land_area).strip()
        farmer_category = request.form.get("farmer_category", "General").strip() or "General"

    # Query filters
    search_q = request.args.get("search", "").strip().lower()
    filter_category = request.args.get("category", "").strip()
    filter_eligibility = request.args.get("eligibility", "").strip().lower()

    CATEGORIES_ORDER = [
        "Crop-specific schemes/support",
        "General farmer assistance schemes",
        "Irrigation schemes",
        "Crop insurance",
        "Seeds/input assistance",
        "Farm equipment subsidies",
        "Soil/land improvement",
        "Organic/natural farming",
        "Other agriculture subsidies"
    ]

    grouped_schemes = {cat: [] for cat in CATEGORIES_ORDER}

    for scheme in GOVT_SCHEMES:
        status, reason = check_eligibility(
            scheme,
            country,
            state,
            district,
            recommended_crop,
            land_area,
            farmer_category
        )

        scheme_copy = scheme.copy()
        scheme_copy["status"] = status
        scheme_copy["eligibility_reason"] = reason

        # Search filter
        if search_q:
            searchable_text = " ".join([
                str(scheme.get("name") or "").lower(),
                str(scheme.get("purpose") or "").lower(),
                str(scheme.get("department") or "").lower(),
                str(scheme.get("category") or "").lower()
            ])
            if search_q not in searchable_text:
                continue

        # Category filter
        scheme_cat = str(scheme.get("category") or "").strip()
        if filter_category and scheme_cat != filter_category:
            continue

        # Eligibility filter
        if filter_eligibility:
            if filter_eligibility == "eligible" and status != "eligible":
                continue
            if filter_eligibility == "ineligible" and status != "ineligible":
                continue
            if filter_eligibility == "unconfirmed" and status != "unconfirmed":
                continue

        if scheme_cat in grouped_schemes:
            grouped_schemes[scheme_cat].append(scheme_copy)

    return render_template(
        "schemes.html",
        grouped_schemes=grouped_schemes,
        categories=CATEGORIES_ORDER,
        selected_category=filter_category,
        selected_eligibility=filter_eligibility,
        search_q=search_q,
        country=country,
        state=state,
        district=district,
        recommended_crop=recommended_crop,
        land_area=land_area,
        farmer_category=farmer_category
    )

@app.route("/scheme-apply")
@login_required
def scheme_apply():
    """Display official government scheme details and direct portal link."""
    scheme_id = request.args.get("scheme", "").strip()

    scheme = next(
        (item for item in GOVT_SCHEMES if str(item.get("id", "")) == scheme_id),
        None
    )

    if not scheme:
        flash("Government scheme not found.", "danger")
        return redirect(url_for("schemes"))

    if not scheme.get("url"):
        flash("Official scheme portal not found.", "danger")
        return redirect(url_for("schemes"))

    return render_template("scheme_apply.html", scheme=scheme)

# -------------------------------------------------------------
# REST API ENDPOINTS
# -------------------------------------------------------------

@app.route("/api/crop_info/<crop_name>")
def api_crop_info(crop_name):
    """REST API endpoint returning JSON crop information."""
    crop_name = str(crop_name).strip()
    if crop_name in crop_database:
        return jsonify(crop_database[crop_name])
    return jsonify({"error": "Crop not found"}), 404

# -------------------------------------------------------------
# APPLICATION ENTRYPOINT
# -------------------------------------------------------------

if __name__ == "__main__":
    if "--check-smtp" in sys.argv:
        raise SystemExit(0 if check_smtp_connection() else 1)

    host = os.environ.get("FLASK_RUN_HOST", "0.0.0.0")
    port = int(os.environ.get("FLASK_RUN_PORT", 5000))

    print(f"[OK] CROPWISE AI starting on http://127.0.0.1:{port}")
    app.run(
        debug=True,
        host=host,
        port=port
    )